[access_combined]
SHOULD_LINEMERGE = false
EXTRACT-action = action=(?<action>[^&\s"]+)
EXTRACT-product_id = product_id=(?<product_id>[^&\s"]+)
EXTRACT-uid = uid=(?<uid>[^&\s"]+)
EXTRACT-JSESSIONID = JSESSIONID=(?<JSESSIONID>[^&\s"]+)
EXTRACT-platform = \((?<platform>Linux; Android [0-9.]+|Macintosh; Intel Mac OS X [0-9_]+|Windows|iPhone; CPU iPhone OS [0-9_]+)
